#!/usr/bin/env node
/**
 * One command to run oneix locally: `npm start`.
 *
 * 1. Creates .env from .env.example on the first run, with a fresh encryption key, then stops so
 *    you can add Zendesk values for the development tenant.
 * 2. Checks Docker is running and starts PostgreSQL and Redis.
 * 3. Installs dependencies if needed.
 * 4. Applies database migrations and builds the apps.
 * 5. Connects the development tenant from ZENDESK_* values, unless it is already connected.
 * 6. Runs api, worker, and web in watch mode.
 *
 * Every step is safe to repeat, so the same command works on every run.
 */
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { appendFileSync, copyFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envFile = join(root, ".env");
const composeFile = "infra/docker/docker-compose.yml";

function step(message) {
  console.log(`\n\x1b[1m▸ ${message}\x1b[0m`);
}

function fail(message) {
  console.error(`\n\x1b[31m✖ ${message}\x1b[0m\n`);
  process.exit(1);
}

/** Runs a command in the repo root with inherited output. Returns true on success. */
function run(command, { quiet = false } = {}) {
  const result = spawnSync(command, {
    cwd: root,
    shell: true,
    stdio: quiet ? "ignore" : "inherit",
  });
  return result.status === 0;
}

// 1. Environment file
const firstRun = !existsSync(envFile);
if (firstRun) copyFileSync(join(root, ".env.example"), envFile);

// Tenant credentials are encrypted with this key. Losing it means reconnecting every tenant.
if (!/^ONEIX_ENCRYPTION_KEY=.+/m.test(readFileSync(envFile, "utf8"))) {
  const key = randomBytes(32).toString("base64");
  appendFileSync(envFile, `\n# Generated by npm start. Keep it: stored tenant credentials need it.\nONEIX_ENCRYPTION_KEY=${key}\n`);
  console.log("Generated ONEIX_ENCRYPTION_KEY in .env.");
}

if (firstRun) {
  console.log("\nCreated .env from .env.example.");
  console.log("Fill in the Zendesk values for your development tenant (see README → Connecting Zendesk),");
  console.log("then run `npm start` again.\n");
  process.exit(0);
}

process.loadEnvFile(envFile);

// 2. Docker services
step("Checking Docker");
if (!run("docker info", { quiet: true })) {
  fail("Docker is not running. Start Docker Desktop and try again.");
}

step("Starting PostgreSQL and Redis");
if (!run(`docker compose -f ${composeFile} up -d --wait`)) {
  fail("Could not start the database containers. See the output above.");
}

// 3. Dependencies
if (!existsSync(join(root, "node_modules"))) {
  step("Installing dependencies");
  if (!run("npm install")) fail("npm install failed.");
}

// 4. Database and build
step("Applying database migrations");
if (!run("npm run migrate:deploy -w @oneix/db")) fail("Migrations failed.");

step("Building the apps");
if (!run("npx turbo run build --output-logs=errors-only")) fail("The build failed. See the output above.");

// 5. Development tenant
step("Connecting the development tenant");
if (!run("npm run tenant --silent -- bootstrap")) {
  fail("Could not connect the development tenant. Check the ZENDESK_* values in .env.");
}

// 6. Apps
step("Starting api, worker, and web (Ctrl+C to stop)");
console.log("  Workspace: http://localhost:3000");
console.log("  API:       http://localhost:4000\n");
const dev = spawnSync("npx turbo run dev", { cwd: root, shell: true, stdio: "inherit" });
process.exit(dev.status ?? 0);
